In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import shutil
import sys
import time
import pprint
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler

from tensorflow import keras

# print(tf.__version__)
# print(sys.version_info)
# for module in mpl, np, pd, sklearn, tf, keras:
#     print(module.__name__, module.__version__) 

# 常量
t_scalar = tf.constant(1)                              #标量
t_vector = tf.constant([1.,2.,3.])                     #矢量
t_matrix = tf.constant([[1.,2.,3.],[4.,5.,6.],[7,8,9]])        #矩阵
t = t_matrix
print(t_scalar)
print(t_vector)
print(t_vector[:2])
print(t_matrix[:,1:])
print(t_matrix[...,1])

# 操作算符
for t in (t_scalar,t_vector,t_matrix):
    print(t+10)
    print(tf.square(t))
    
    
print(tf.transpose(t_matrix))             #矩阵转置
print(t_matrix @ tf.transpose(t_matrix))  #矩阵乘法
print(t_matrix * tf.transpose(t_matrix))  #矩阵内每个元素相乘

# tf 和 numpy 转化
print(t.shape)
print(t.numpy())                   
print(type(t.numpy()))               #将t转化成numpy
print(np.square(t))                  #可以直接和numpy一起使用
print(type(np.square(t)))            #可以和np一起使用
np_t = np.array(
    [[1.,2.,3.],
     [4.,5.,6.]])
print(np_t.shape)
print(tf.constant(np_t))                    #转化成tensorflow 常量

#scalar
t = tf.constant(2.718)
print(t)
print(t.numpy())
print(t.shape)

# strings
t = tf.constant("cafe")
print(t)
print(tf.strings.length(t))
print(tf.strings.length(t,unit="UTF8_CHAR"))
print(tf.strings.unicode_decode(t,"UTF8"))        #转化成UTF-8字符

# string array
t = tf.constant(["cafe","coffee","咖啡"])
print(tf.strings.length(t,unit="UTF8_CHAR"))
r = tf.strings.unicode_decode(t,"UTF8")
print(r)

#ragged tensor
r = tf.ragged.constant([[11,12],[21,22,23],[],[41]])
print(r)
print(r[1])
print(r[1:2])

r2 = tf.ragged.constant([[51,52],[],[71]])
print(tf.concat([r,r2],axis=0))

r3 = tf.ragged.constant([[13,14],[15],[1,2],[42,43]])
print(tf.concat([r,r3],axis=1))
print((tf.concat([r,r3],axis=1)).to_tensor())
print(r.to_tensor())

#sparse tensor
s = tf.SparseTensor(indices=[[0,1],[1,0],[2,3]],
                   values = [1,2,3],
                   dense_shape=[3,4])
print(s)
print(tf.sparse.to_dense(s))


# ops on sparse tensors
#?? float is not useable
s2 = s * 2
print(s2)

try:
    s3 = s + 1
except TypeError as ex:
    print(ex)

s4 = tf.constant([[10.,20.],
                 [30.,40.],
                 [50.,60.],
                 [70.,80.]])
print(tf.sparse.sparse_dense_matmul(s,s4))

#sparse tensor
s5 = tf.SparseTensor(indices=[[1,0],[0,1],[2,3]],
                   values = [1,2,3],
                   dense_shape=[3,4])
print(s5)
s6 = tf.sparse.reorder(s5)
print(tf.sparse.to_dense(s6))


#Variables
v = tf.Variable([[1.,2.,3.],[4.,5.,6.]])
print(v)
print(v.value())
print(v.numpy())

#assign value
v.assign(2*v)      #赋值
print(v.numpy())
v[0,1].assign(42)
print(v.numpy())
v[1].assign([7.,8.,9.])
print(v.numpy())

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([1. 2.], shape=(2,), dtype=float32)
tf.Tensor(
[[2. 3.]
 [5. 6.]
 [8. 9.]], shape=(3, 2), dtype=float32)
tf.Tensor([2. 5. 8.], shape=(3,), dtype=float32)
tf.Tensor(11, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([11. 12. 13.], shape=(3,), dtype=float32)
tf.Tensor([1. 4. 9.], shape=(3,), dtype=float32)
tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]
 [17. 18. 19.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 14.  32.  50.]
 [ 32.  77. 122.]
 [ 50. 122. 194.]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.  8. 21.]
 [ 8. 25. 48.]
 [21. 48. 81.]], shape=(3, 3), dtype=float32)
(3, 3)
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
<class 'numpy.ndarray'>
[[ 1.  4.  9.]
 [16. 25. 36.]
 [49. 64. 81.]]
<class 'numpy.ndarray'>
(2, 

InvalidArgumentError: cannot compute SparseTensorDenseMatMul as input #3(zero-based) was expected to be a int32 tensor but is a float tensor [Op:SparseTensorDenseMatMul]

In [5]:
t = tf.constant([1,2,3])
print(np.array(t))
t.numpy()

[1 2 3]


array([1, 2, 3], dtype=int32)

In [8]:
t = tf.SparseTensor(indices=
                    [[0,0],[1,1],[2,2],[3,3]],
                   values = [1,2,3,4],
                   dense_shape = [4,4])

In [9]:
tf.sparse.to_dense(t)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]], dtype=int32)>

In [23]:
c = tf.ragged.constant([[1,2,3,4],[5,6,7,8]])
d = tf.ragged.constant([[1,2],[3,4]])
e = tf.transpose((tf.concat([c,d],axis=0)).to_tensor())
print(e)

tf.Tensor(
[[1 5 1 3]
 [2 6 2 4]
 [3 7 0 0]
 [4 8 0 0]], shape=(4, 4), dtype=int32)


In [24]:
tf.sparse.sparse_dense_matmul(t,e)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  5,  1,  3],
       [ 4, 12,  4,  8],
       [ 9, 21,  0,  0],
       [16, 32,  0,  0]], dtype=int32)>